extends: default

rules:
  document-start: disable
  line-length:
    max: 140
    allow-non-breakable-words: true
  truthy:
    check-keys: false
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

ignore: |
  docs/**
  semaphore/**

